[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anteroom = "EbGkJPaMY8XCJCNjkWwk971xzE32X5LBPg5s2g4LDYcW"
buy-in = "CLC46PuyXnSuZGmUrqkFbAh7WwzQm8aBPjSQ3HMP56kp"
cash-out = "BAP315i1xoAXqbJcTT1LrUS45N3tAQnNnPuNQkCcvbAr"
eat-food = "EdLga9mFADH4EjPY6RsG1LF7w8utVuWDgyLVRrA8YzzN"
eat-player = "F6rDhVKjVTdGKdxEK9UWfFDcxeT3vFbAckX6U2aWeEKZ"
exit-game = "wdH5MUvXcyKM58yffCxhRQfB5jLQHpnWZhhdYhLCThf"
init-anteroom = "AxmRc9buNLgWVMinrH2WunSxKmdsBXVCghhYZgh2hJT6"
init-map = "NrQkd31YsAWX6qyuLgktt4VPG4Q2DY94rBq7fWdRgo7"
init-player = "58N5j49P3u351T6DSFKhPeKwBiXGnXwaYE1nWjtVkRZQ"
init-section = "4euz4ceqv5ugh1x6wZP3BsLNZHqBxQwXcK59psw5KeQw"
map = "2dZ5DLJhEVFRA5xRnRD779ojsWsf3HMi6YB1zmVDdsYb"
movement = "9rthxrCfneJKfPtv8PQmYk7hGQsUfeyeDKRp3uC4Uwh6"
player = "2ewyq31Atu7yLcYMg51CEa22HmcCSJwM4jjHH8kKVAJw"
section = "BEox2GnPkZ1upBAdUi7FVqTstjsC4tDjsbTpTiE17bah"
spawn-food = "GP3L2w9SP9DASTJoJdTAQFzEZRHprMLaxGovxeMrvMNe"
spawn-player = "DViN676ajvuWryjWHxk2EF7MvQLgHNqhj4m32p1xLBDB"

[programs.localnet]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "devnet"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
